---
- name: Configure WordPress Database
  hosts: web
  become: yes

  tasks:

    - name: Create database
      shell: |
        mysql -e "CREATE DATABASE IF NOT EXISTS wordpressdb;"

    - name: Create user
      shell: |
        mysql -e "CREATE USER IF NOT EXISTS 'wpuser'@'localhost' IDENTIFIED BY 'StrongPassword123!';"

    - name: Grant privileges
      shell: |
        mysql -e "GRANT ALL PRIVILEGES ON wordpressdb.* TO 'wpuser'@'localhost'; FLUSH PRIVILEGES;"
